name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Install dependencies
      - name: Install dependencies
        run: |
            npm install --legacy-peer-deps


      # Run SonarQube analysis
      - uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"
        
      # Run tests with Angular CLI
      - name: Run Angular tests
        run: |
          ng test --watch=false --browsers=ChromeHeadless --code-coverage

      # If you want to add the quality gate check, uncomment below
      # - uses: sonarsource/sonarqube-quality-gate-action@v2
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
